### ISSUE TITLE
Conformal scores with respect to predictive density

### ISSUE THREAD

**Issue by pat-alt** [CoryMcCartan/conformalbayes#1]
Hi @CoryMcCartan! Cool package 👍🏽 I want to add support for Conformalized Bayes in my [Julia package](https://github.com/pat-alt/ConformalPrediction.jl) as outlined [here](https://arxiv.org/pdf/2107.07511.pdf) (Section 2.4, pp 10-11). I just had a look at your code for some inspiration and want to make sure I understand correctly: it looks like you're conformalizing point predictions (drawn from the posterior), is that right? In other words, conformal scores are not computed with respect to the posterior predictive density as described in the linked tutorial.

Thanks in advance!

**Comment by CoryMcCartan** [comment]
Hi!  Currently I basically expand a normal posterior quantile interval by a scaling factor set with conformal inference.  So I'm not yet doing the level-set-based thing described on p. 11 of the paper you sent.  Looks like that's probably a superior method, though, so I'll probably implement it if I ever get around to it.

**Comment by pat-alt** [comment]
Thanks!
